[Issue#20] Enable play button from Home > Episodes list
SaraHan774/Jetcaster pull request #30
Opened 2024-01-24 15:55 UTC by SaraHan774

- 더 생각해볼 지점들이 좀 있는데, 마일스톤 끝나는 시점이라 미리 draft 올립니다. 
- 현재 재생중인 미디어 아이템인지 판별하는 로직이 마음에 들지 않아요 ... (currently I am comparing the title of the episode & MediaItem's displayTitle) 
- SelectedEpisode 와 같은 데이터 클래스 도입이 마음에 들지 않아요 ... 
  - 현재 Jetcaster 에서는 Database 모델과 UiState 객체들이 섞여있는데, 이를 정리할 필요가 있을지 고민입니다.

2024-01-27 13:57 UTC, tuvakov requested changes

2024-01-27 13:57 UTC, tuvakov commented on app/src/main/java/com/august/jetcaster/ui/home/category/PodcastCategory.kt
> +        val icon = if (isPlaying) {
Loading 상태도 보여 줘야 될 것 같아요. 그래서 PlayButton이나 그 안에 있는 로직을 공통으로 사용할 수 있게 하는 것이 어떨까요?
그 쪽은 기존에도 parameter로 넘어가는 것이 많긴 한데 무리라고 생각하시면 따로 하셔도 좋아요.

2024-01-27 13:57 UTC, tuvakov commented on app/src/main/java/com/august/jetcaster/ui/home/category/PodcastCategoryViewModel.kt
> +    private val _selectedEpisode = MutableSharedFlow<SelectedEpisode>(
이 state를 내부적으로 관리하면 문제가 될 수 있어요. play 호출하면 여기가 바로 업데이트 될 거예요. 그런데 어떤 이유로 media service가 play 시작 못 하면은 요 state (UI)이랑 실제 재생 상태 사이에 차이 있을 거예요. 그래서 MediaBus.state를 collect 해서 UI state를 그걸로 만드는 것이 좋을 것 같아요.

추가로 현재

1. EpisodeListItem에 있는 play 버튼을 통해 재생을 시작
2. 다른 episode를 모든 영역에 click 해서 시작 (PlayerScreen으로 이동함)
3. 다시 홈 화면으로 이동

이때 episode list가 제대로 업데이트 안 되예요. 서로 보고 있는 state가 달라서요..

2024-01-27 13:57 UTC, tuvakov commented on app/src/main/java/com/august/jetcaster/ui/home/category/PodcastCategoryViewModel.kt
> +                // FIXME : 이렇게 비교하는건 불안정해 보이는데 다른 방법 찾아야 한다
새로운 MediaEvent를 만들어서 아래 로직을 media service에서 하는 것이 어떨까요?

2024-01-27 14:00 UTC, tuvakov commented
> 현재 재생중인 미디어 아이템인지 판별하는 로직이 마음에 들지 않아요 ... (currently I am comparing the title of the episode & MediaItem's displayTitle)

`MediaState`에 uri 추가해서 그걸 이용하는 방법도 있는 것 같아요.

2024-02-06 15:27 UTC, SaraHan774 commented on app/src/main/java/com/august/jetcaster/ui/home/category/PodcastCategoryViewModel.kt
> +    private val _selectedEpisode = MutableSharedFlow<SelectedEpisode>(
MediaBus 를 구독하도록 변경했습니다.

2024-02-06 15:27 UTC, SaraHan774 commented on app/src/main/java/com/august/jetcaster/ui/home/category/PodcastCategory.kt
> +        val icon = if (isPlaying) {
Loading 은 일단 따로 넣어봤어요. 
> PlayButton이나 그 안에 있는 로직을 공통으로 사용할 수 있게 하는 것이 어떨까요? 
이부분 좀 더 알아볼게요

2024-02-06 15:40 UTC, SaraHan774 commented on app/src/main/java/com/august/jetcaster/ui/home/category/PodcastCategory.kt
> +        val icon = if (isPlaying) {
홈 화면 리스트에서는 constraint modifier 를 사용하고 있어서 공통 로직을 추출하면 CircularProgress 와 IconButton 에 대한 modifier 를 인자로 넘겨주어야 할 것 같은데, 좋은 practice 같지는 않아보여요. 일단은 따로 둘게요.

2024-02-06 15:41 UTC, SaraHan774 commented on app/src/main/java/com/august/jetcaster/ui/home/category/PodcastCategoryViewModel.kt
> +    private val _selectedEpisode = MutableSharedFlow<SelectedEpisode>(
아무래도 이전에 코드 짤 때 많이 피곤한 상태였던 것 같아요 .. ;;

2024-02-07 14:31 UTC, SaraHan774 commented on app/src/main/java/com/august/jetcaster/ui/home/category/PodcastCategoryViewModel.kt
> +                // FIXME : 이렇게 비교하는건 불안정해 보이는데 다른 방법 찾아야 한다
MediaService 에서 판별하는건 어떤 방식인지 잘 이해를 못했어요

2024-02-17 11:28 UTC, tuvakov commented on app/src/main/java/com/august/jetcaster/ui/home/category/PodcastCategoryViewModel.kt
> +                // FIXME : 이렇게 비교하는건 불안정해 보이는데 다른 방법 찾아야 한다
`SetOrPlay` 같은 event 만들고 그걸 서비스로 넘기면 서비스 내부에서 set 할지 play 할지 판단을 하는 방식을 말한 것이였어요.

2024-02-17 11:29 UTC, tuvakov approved these changes
Pause 하는 데 버그 있었는데 제가 고쳤어요.

2024-02-17 11:30 UTC, merged